name: CI Pipeline

on:
  push:
    branches:
      - main  # Triggers the action on a push to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the action on a pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your code from the repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can specify the version of Python you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run migrations
        run: |
          cd hotelsite
          python manage.py migrate  # Apply migrations

      - name: Run tests
        run: |
          cd hotelsite
          pytest  # Run automated tests using pytest

      - name: Run Flake8 for linting
        run: |
          flake8 hotelsite --max-line-length=88  # Check for code quality issues

      - name: Run coverage
        run: |
          coverage run -m pytest  # Run tests with coverage
          coverage report  # Display the coverage report
