name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run migrations
        run: |
          cd hotelsite
          python manage.py migrate  # Apply migrations (SQLite doesn't need a service setup)

      - name: Run tests
        run: |
          cd hotelsite
          python manage.py test  # Run Django tests
