name: CI Pipeline

on:
  push:
    branches:
      - main  # Triggers the action on a push to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the action on a pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment where the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your code from the repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate  # Apply migrations (SQLite doesn't need a service setup)

      - name: Run tests
        run: |
          python manage.py test  # Run Django tests
