name: CI Pipeline

on:
  push:
    branches:
      - main  # Triggers the action on a push to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the action on a pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment where the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your code from the repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Run migrations if your Django project needs them
      - name: Run migrations
        run: |
          cd hotelsite
          python manage.py migrate  # Apply migrations

      # Step 1: Run pytest for automated tests
      - name: Run tests with pytest
        run: |
          cd hotelsite
          pytest --cov  # Run tests with coverage report

      # Step 2: Run flake8 for code style checks (PEP 8)
      - name: Run code style checks with flake8
        run: |
          flake8 hotelsite/  # Run flake8 to check code style

      # Step 3: Run mypy for static type checks (Optional but useful)
      - name: Run type checks with mypy
        run: |
          mypy hotelsite/  # Run mypy to check type annotations
